### ISSUE TITLE
Too little useful information about the working group in the README

### ISSUE THREAD

**Issue by vi** [rust-lang/wg-binary-size#1]
I expected to see a roadmap, some links to (pre)RFCs, discussions threads on IRLO, links to Zulip or at least a number of Gihub issues that this working group will be dealing with.

**Comment by nnethercote** [comment]
The working group has only just started. We haven't even had a meeting yet.

**Comment by thomcc** [comment]
https://hackmd.io/BPiMVIcYQ_2svaAsOMktog contains most of the info so far.

We decided in the [meeting on 2023-11-30](https://rust-lang.zulipchat.com/#narrow/stream/405744-wg-binary-size/topic/Meeting.202023-11-30) that we should add a link to this document in the README (PRs welcome, or I'll try to get to it this weekend).
